In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np
import pandas as pd

import warnings

warnings.filterwarnings('ignore')

In [3]:
a = np.array([10, 11, "aa", "bb", 45, 88])
a.dtype
print(a)

['10' '11' 'aa' 'bb' '45' '88']

In [4]:
S = pd.Series(a, index=list(range(10, 16)))
S

10    10
11    11
12    aa
13    bb
14    45
15    88
dtype: object

In [5]:
S.loc[10:15]

10    10
11    11
12    aa
13    bb
14    45
15    88
dtype: object

In [6]:
lt=[10, 11, "aa", "bb", 45, 88]

In [7]:
mydic={"Snake":0, "Leapord":2, "Cow":5, "Human": 8}
myD=pd.Series(mydic)
myD

Snake      0
Leapord    2
Cow        5
Human      8
dtype: int64

In [8]:
s=pd.Series(100, index = list(range(5,10)))
s

5    100
6    100
7    100
8    100
9    100
dtype: int64

In [10]:
THARVAdf=pd.read_excel("/content/German-Credit_1.xls")

FileNotFoundError: [Errno 2] No such file or directory: '/content/German-Credit_1.xls'

In [11]:
THARVAdf=pd.read_excel("/content/German-Credit_1.xls")

FileNotFoundError: [Errno 2] No such file or directory: '/content/German-Credit_1.xls'

In [ ]:
df.head()

In [ ]:
df.tail(5)

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.info()

In [ ]:
df_sub = df["EDUCATION"]
df_sub.head()

In [ ]:
df.mean()

In [ ]:
df.std()

In [ ]:
df.describe(include = "all")

In [ ]:
df.loc[1:5,"NEW_CAR":"AMOUNT"]

In [ ]:
df.iloc[1:5,2:9]

In [ ]:
mean_AMOUNT = df["AMOUNT"].mean()
print(mean_AMOUNT)